name: widget_catalog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  widgetbook_demo:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.16.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
